--- #YAML:1.0
name:                Pg-Loader
version:             0.05
abstract:            Perl extension for loading Postgres tables
license:             ~
author:              
    - Ioannis Tambouras <ioannis@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Config::Format::Ini:           0.05
    Data::Dumper:                  2.121_08
    DBD::Pg:                       2.8.1
    Getopt::Compact:               0.04
    List::MoreUtils:               0.22
    Log::Log4perl:                 1.16
    Quantum::Superpositions:       2.02
    Test::Exception:               0.27
    Test::MockDBI:                 0.61
    Test::Pod:                     1.0
    Test::Pod::Coverage:           1.0
    Text::CSV:                     1.06
    Time::HiRes:                   1.9711
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
